-- Migration 0027: Carrier tracking, postponement, and IP tracking columns
-- NOTE: carrier_status, postponed_until, customer_ip were already added in 0025.
-- This migration is intentionally empty to avoid duplicate column errors.
