-- Migration 0034: FK cascade constraints
-- NOTE: SQLite does not support ALTER TABLE ADD CONSTRAINT.
-- Foreign keys are defined in CREATE TABLE statements where possible.
-- CASCADE behavior is enforced at the application layer.
